# This file was generated by GoReleaser. DO NOT EDIT.
cask "yoink" do
  version "0.0.1"

  on_macos do
    sha256 "b41dae1586269e0635999be632d10d6014e6393bb35f0c2f9085e26eb758ba9a"
    url "https://github.com/davcevski/yoink/releases/download/v#{version}/yoink_#{version}_darwin_all.tar.gz"
  end

  name "yoink"
  desc "An encrypted macOS clipboard history with a terminal UI"
  homepage "https://github.com/davcevski/yoink"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "yoink"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/yoink"]
  end

  uninstall launchctl: [
      "com.yoink.daemon",
    ]

  zap trash: [
      "~/.config/yoink",
      "~/Library/LaunchAgents/com.yoink.daemon.plist",
    ]

  caveats <<~EOS
    Start the background capture daemon (runs at login) once with:
      yoink install

    yoink encrypts your clipboard history at rest with a key kept in the macOS
    Keychain. Enabling FileVault is recommended for full at-rest protection.

    Remove the daemon any time with:
      yoink uninstall
  EOS
end
